### ISSUE TITLE
"Output from the virtualenvwrapper hook post_activate:" buffer keeps appearing

### ISSUE THREAD

**Issue by jeffpollock9** [jorgenschaefer/pyvenv#102]
Hi,

Firstly, thanks for a great package :)

Secondly, After upgrading to emacs27.1 and also upgrading to the latest pyvenv, I keep getting a buffer with:

```
Output from the virtualenvwrapper hook post_activate:
```

appearing every time I change the virtualenv via `pyvenv-workon` or `pyvenv-activate` which is quite annoying. Running e.g. `workon my-env` in the terminal works as per normal.

I expect it's probably me doing something wrong (my emacs-fu is very poor), but I'm really stumped by this and have resorted to just deleting some code in my local install to stop this - any help to a proper fix would be amazing.

my init.el is [here](https://github.com/jeffpollock9/.emacs.d/blob/master/init.el) and I think the relevant lines are:

``` elisp
  (use-package pyvenv
    :ensure t
    :bind
    (:map pyvenv-mode-map
          ("C-c q" . pyvenv-restart-python)
          ("C-c o" . pyvenv-workon))
    :init
    (pyvenv-mode)
    (pyvenv-tracking-mode)
    :config
    (pyvenv-workon "pymacs"))
```

thanks!

**Comment by Cerebus** [comment]
From what I can tell, virtualenvwrapper hooks are returning a single byte of output.  I'm currently using virtualenvwrapper 4.8.4.

Changing this line:

https://github.com/jorgenschaefer/pyvenv/blob/d6844d5beeb5f8093d98091a2931f38dd891476b/pyvenv.el#L449

To:

```emacs-lisp
when (> (length output) 1)
```
Makes the symptom go away.

**Comment by gaetano-guerriero** [comment]
`(let ((output (string-trim (buffer-substring hook-output-start-pos` could be safer,
 I've opened #103

**Comment by jeffpollock9** [comment]
Thanks all for the comments, I've started using #103 which fixes this, would be great to get that, or similar, merged in.
