### ISSUE TITLE
Update README to make clear this package has no relation to the pyvenv script that was shipped with Python 3

### ISSUE THREAD

**Issue by doolio** [jorgenschaefer/pyvenv#104]
Just starting the journey in trying to wrap my head around all things related to python virtual environments! I appreciate the `pyvenv` script that was shipped with Python 3 has been [deprecated since Python 3.6](https://docs.python.org/dev/whatsnew/3.6.html#id8) but I initially assumed this package was an Emacs interface to that script. I presume that is not the case. Perhaps make that clear in the README.

Am I also correct in assuming this package creates and manages virtual environments either using `virtualenv/virtualenvwrapper.sh` (I assume both are needed?) or `venv` from the python standard library favouring `virtualenv/virtualenvwrapper.sh` if it/they is/are installed. If that is the case, perhaps make that clear in the README too. 

I'm happy to submit a PR if someone can confirm what I've stated here is correct.

**Comment by jorgenschaefer** [comment]
pyvenv.el uses the venv module of Python 3 and was originally intended as the Emacs version of the shell script, which also was nothing but a wrapper around said module.

It also supports virtualenvwrapper when it is installed and configured, but does not require its use.

I have no idea how many people are confused by the naming. If you can come up with a small change to the README that addresses your confusion, feel free to submit a PR, but I do not generally like long explanations of what a project is NOT in its README.

**Comment by doolio** [comment]
Thank you for the quick response and the background. I had assumed this package was developed initially for `virtualenv` and later supported `venv` from the python standard library. Your explanation here makes things clearer and could perhaps serve in avoiding my confusion for others rather than updating the README. Therefore, I think we can close this issue.
