### ISSUE TITLE
(json-readtable-error (80)) error when I pyvenv-activate

### ISSUE THREAD

**Issue by Charlescad** [jorgenschaefer/pyvenv#117]
Hello,
After having installed emacs 27.2 on windows 10, I get this json-readtable-error (80) when I try to pyvenv-activate.
The error was thrown on the spacemacs package https://github.com/syl20bnr/spacemacs/issues/15026.
Is there uncompatibility between emacs 27.2 and pyvenv on windows? I will downgrade my emacs version to 26 for now but I would be glad helping finding a patch even though I am not an elisp expert.

**Comment by Charlescad** [comment]
I reinstalled everything and the problem disappeared...

**Comment by mhlinder** [comment]
@Charlescad When you say you "reinstalled everything", what specifically did you reinstall?

I am using `pyvenv-workon` and encountering a `json-read` error, as well:
```
Debugger entered--Lisp error: (json-readtable-error 112)
  signal(json-readtable-error (112))
  json-read()
  pyvenv-run-virtualenvwrapper-hook("pre_activate" nil "/Users/henry/.pyenv/versions/science/")
  pyvenv-activate("/Users/henry/.pyenv/versions/science/")```
