### ISSUE TITLE
VIRTUALENVWRAPPER_HOOK_DIR not exported anymore

### ISSUE THREAD

**Issue by jorgenschaefer** [jorgenschaefer/pyvenv#25]
Recent versions of virtualenvwrapper – e.g. 4.3.1 – do not export this variable anymore, which means we can't rely on it in Emacs anymore.

Originally reported in jorgenschaefer/elpy#497

**Comment by ChillarAnand** [comment]
hi, can you please tell me, which version are you using?

**Comment by jorgenschaefer** [comment]
3.4 :-)
