### ISSUE TITLE
anaconda integration

### ISSUE THREAD

**Issue by cpaulik** [jorgenschaefer/pyvenv#29]
Hi,

Anaconda-mode tracks the status of the variable
`python-shell-virtualenv-path` to automatically switch between virtual environments for autocompletion.

Would it be possible to set this variable to the path of the virtualenv when switching with pyvenv?

I've already hacked together a small function for spacemacs that does the trick but I guess out of the box compatibility would be nice.

```elisp
            (defun spacemacs/pyvenv-workon ()
              "switch python virtualenvironment and restart anaconda server"
              (interactive)
              (call-interactively 'pyvenv-workon)
              (setq python-shell-virtualenv-path pyvenv-virtual-env))
```

**Comment by jorgenschaefer** [comment]
Good idea! I didn't know about that variable :-)
