### ISSUE TITLE
No statusbar msg when using pyvenv-activate

### ISSUE THREAD

**Issue by flub** [jorgenschaefer/pyvenv#30]
Hi,

When using `pyvenv-workon` you get to see the name of the activated virtualenv in the status bar (`[envname]`).  However it seems when using `pyvenv-activate` to select a path you simply get `[]` instead of an env name.

It would be nice if it could show the basename of the environment.  While this could conflict it could be possible to keep a list of previously activated environments and once the basename starts to conflict disambiguate it like emacs does for buffer names by finding the first parent which differs.  E.g. for `/tmp/foo/env/` and `/tmp/bar/env/` once the 2nd env is activated one could show `[foo/env]` and `[bar/env]` instead of just `[env]`.

Alternatively simply showing the full path might be suitable too, if a little verbose.  Probably wouldn't work so well on small screens.

Regards,
Floris

**Comment by jorgenschaefer** [comment]
`pyvenv-activate` actually uses `file-name-nondirectory` on the passed directory, which works if there is no trailing slash, but I think it breaks for a path with a trailing slash. That's a bug! Thanks for the report :-)

**Comment by flub** [comment]
Oh, indeed.  Without a trailing slash it shows up fine.  It's just that emacs autocompletion gives a trailing slash by default.  Thanks!
