### ISSUE TITLE
pyvenv-activate uses a bad check to detect virtualenvwrapper

### ISSUE THREAD

**Issue by deadlytackler5** [jorgenschaefer/pyvenv#31]
Started with `M-x jedi:install-server`
it responded with-
`python-environment--make-with-runner: Program named "virtualenv" does not exist.`
... so downloaded pyvenv.el, which again wanted to know the directory address. Assuming it wants the address of some virtualenv created virtual environment through cmd.exe with command-
`c:\Python34\python -m pyvenv akkenv`
which created a directory (akkenv)at -
`:\Windows\System32`
Installed Pyvenv.el through M-x list-package tried to activate it through `M-x pyvenv-activate` showed him akkenv however it seems he wants to go further deep down as [ ] was nowhere...where should I lead him to?
My akkenv directory shows following folders
`Include`
`Lib`
`Scripts`
`pyvenv.cfg (which is not accessible when I am pointing towards it in minibuffer)`
my .emacs related to jedi is something like this at present -
```
;;Jedi
(require 'jedi)
(setq jedi:server-command "~/.emacs.d/jediepcserver.py")
(add-hook 'python-mode-hook 'jedi:setup)
(setq python-environment-virtualenv "C:/Windows/System32/arunenv")
;; Hook up to autocomplete
(add-to-list 'ac-sources 'ac-sources-jedi-direct)
;; Enable for python-mode
;;(add-hook 'python-mode-hook 'jedi:setup)
;; python-interpreter
(setq python-shell-interpreter "C:/Python34/python.exe")

;; EPC for Jedi
(require 'epc)

;; Local Jedi keybindings
(defun jedi-config:setup-keys ()
  (local-set-key (kbd "M-.") 'jedi:goto-definition)
  (local-set-key (kbd "M-,") 'jedi:goto-definition-pop-marker)
  (local-set-key (kbd "M-?") 'jedi:show-doc)
  (local-set-key (kbd "M-/") 'jedi:get-in-function-call))

  (add-hook 'python-mode-hook 'jedi-config:setup-keys)
  ;; Never show in-function call automatically
  (setq jedi:get-in-function-call-delay 10000000)
  ;; Complete when type a dot
  (setq jedi:complete-on-dot t)
```
Am I supposed to add/delete something ?

Where am I faulting ?
pyvenv version 20150503.941

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report!

`M-x pyvenv-activate` does expect the virtualenv directory, the one that includes the `Include`, `Scripts` etc. directories. Does that solve your problem? :-)

**Comment by deadlytackler5** [comment]
akkenv has `Include`, `Scripts`, `Lib` however [ ] is not appearing pressing RET after C:\Windows\System32\akkenv returns `Wrong type argument: stringp, nil`

**Comment by jorgenschaefer** [comment]
Could you do `M-x toggle-debug-on-error`, try to activate the virtualenv again, and post the resulting backtrace here, please?

**Comment by deadlytackler5** [comment]
```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  call-process(nil nil t nil "-c" "from virtualenvwrapper.hook_loader import main; main()" "--script" "c:/Users/arun/AppData/Local/Temp/pyvenv-virtualenvwrapper-9276hbJ" "pre_deactivate")
  apply(call-process nil nil t nil "-c" "from virtualenvwrapper.hook_loader import main; main()" "--script" "c:/Users/arun/AppData/Local/Temp/pyvenv-virtualenvwrapper-9276hbJ" "pre_deactivate")
  pyvenv-run-virtualenvwrapper-hook("pre_deactivate")
  pyvenv-deactivate()
  pyvenv-activate("~/arunenv/")
  call-interactively(pyvenv-activate record nil)
  command-execute(pyvenv-activate record)
  execute-extended-command(nil "pyvenv-activate")
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
```
in between i created another virtualenv at ~/arunenv through cmd.exe

**Comment by deadlytackler5** [comment]
if trying to set akkenv - which is at C:\Windows\System32\akkenv -
```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  call-process(nil nil t nil "-c" "from virtualenvwrapper.hook_loader import main; main()" "--script" "c:/Users/arun/AppData/Local/Temp/pyvenv-virtualenvwrapper-6216jjJ" "pre_deactivate")
  apply(call-process nil nil t nil "-c" "from virtualenvwrapper.hook_loader import main; main()" "--script" "c:/Users/arun/AppData/Local/Temp/pyvenv-virtualenvwrapper-6216jjJ" "pre_deactivate")
  pyvenv-run-virtualenvwrapper-hook("pre_deactivate")
  pyvenv-deactivate()
  pyvenv-activate("c:/Windows/system32/akkenv/")
  call-interactively(pyvenv-activate record nil)
  command-execute(pyvenv-activate record)
  execute-extended-command(nil "pyvenv-activate")
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
```

**Comment by jorgenschaefer** [comment]
The variable `pyvenv-virtualenvwrapper-python` is `nil`, which it should not be – do you use virtualenvwrapper? If so, please set this variable to your virtualenvwrapper python.

If you are not using virtualenvwrapper, I think I just noticed a bug in pyvenv. Try evaluating the following and see if that fixes the problem:

```Lisp
(defun pyvenv-hook-dir ()
  nil)
```

**Comment by deadlytackler5** [comment]
I just evaluated it through `M-: (defun pyvenv-hook-dir ()   nil)`
and then again tried `M-x pyvenv-activate`
no error message this time....

Was it right or was supposed to do something else...

**Comment by jorgenschaefer** [comment]
That should mean that your virtualenv is now active in Emacs. Try `M-x pyvenv-mode`, that will display your current virtualenv in the mode line.

I'll fix this bug in pyvenv, thank you for finding it!

**Comment by deadlytackler5** [comment]
it says pyvenv mode enabled but doesn't show current virtualenv in the modeline...
![modeline](https://cloud.githubusercontent.com/assets/6988525/8125829/cbce2dd0-1106-11e5-8a63-c6051aeb07c3.PNG)

**Comment by jorgenschaefer** [comment]
You are using powerline. I have no idea if powerline supports pyvenv.

Does `M-: (getenv "VIRTUAL_ENV")` show the correct environment?

**Comment by deadlytackler5** [comment]
thanks....it showing..
Once again thanks for being with me really appreciate for hand holding...

**Comment by jorgenschaefer** [comment]
You're very welcome – glad it works! And thank you for reporting this issue. It is a bug after all!
