### ISSUE TITLE
How to set $WORKON_HOME on windows

### ISSUE THREAD

**Issue by xuehao** [jorgenschaefer/pyvenv#32]

**Comment by jorgenschaefer** [comment]
Hello, and thank you for the question! I do not use Windows, so have no idea, but does this page help?
https://virtualenvwrapper.readthedocs.org/en/latest/install.html#windows-command-prompt

**Comment by jorgenschaefer** [comment]
Lacking any further updates on this, I assume the problem is solved and I will close this issue. Please do not hesitate to open a new one if you have any further problems!
