### ISSUE TITLE
slight change to ImportError message between python2 and 3

### ISSUE THREAD

**Issue by tacaswell** [jorgenschaefer/pyvenv#35]
In python3 they added single quotes around the module name in the message of `ImportError`:

```
✔ ~/other_source/elpy [master|✔] 
13:44 $ python2
Python 2.7.10 (default, Sep  7 2015, 13:51:49) 
[GCC 5.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import foo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named foo
>>> 
✔ ~/other_source/elpy [master|✔] 
13:51 $ python
Python 3.5.0 (default, Sep 20 2015, 11:28:25) 
[GCC 5.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import foo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'foo'
>>> 

```

This causes the check on https://github.com/jorgenschaefer/pyvenv/blob/master/pyvenv.el#L374 to pass which results in an un-needed buffer reporting the error.

I can see several ways to fix this, but don't know enough elisp conventions to know which one is preferred.

**Comment by jorgenschaefer** [comment]
Hello, and thanks a lot for the report! Interesting change, good catch on that. :-)

**Comment by tacaswell** [comment]
Thanks for the quick fix.  Just switch to elpy and it is making me very happy.

**Comment by jorgenschaefer** [comment]
Glad to hear so! :-)
