### ISSUE TITLE
pyvenv parsing of virtualenvwrapper hook incompatible with zsh

### ISSUE THREAD

**Issue by elemakil** [jorgenschaefer/pyvenv#36]
In `zsh`, the equal sign can be used to get the full path of an executable, i.e. `=ls` get expanded to `/bin/ls`. However, this makes zsh incompatible with `pyvenv-run-virtualenvwrapper-hook`.

Offending s-expr [lines 370-1]:
```
(format ". '%s' ; echo ; echo =-=-= ; python -c \"import os, json ; print(json.dumps(dict(os.environ)))\""
                       tmpfile)
```
where `echo =-=-=` lacks quotation marks. Inserting those fixes this problem:
```
(format ". '%s' ; echo ; echo \"=-=-=\" ; python -c \"import os, json ; print(json.dumps(dict(os.environ)))\""
                       tmpfile)
```

**Comment by jorgenschaefer** [comment]
Good catch! No idea why `call-process-shell-command` uses the same variable as `shell-mode`, but pyvenv should probably just rebind that to `/bin/sh` there.
