### ISSUE TITLE
/bin/sh: 11: /tmp/pyvenv-virtualenvwrapper-*: source: not found on Ubuntu

### ISSUE THREAD

**Issue by zed** [jorgenschaefer/pyvenv#38]
`(pyvenv-run-virtualenvwrapper-hook)` in `pyvenv.el` sets `shell-file-name` to `/bin/sh` that leads to the error. 

`/bin/sh` on Ubuntu does not understand `source` (it uses `.`).
`virtualenvwrapper` creates hooks that are presumed to be sourced using `$SHELL`.
The hooks such as `post_activate` may contain `source` command explicitly:

```
$VIRTUALENVWRAPPER_PYTHON -c 'from virtualenvwrapper.hook_loader import main; main()' --source post_activate | nl
     1  # project
     2  #
     3  # Change to the project directory, as long as we haven't been told not to.
     4  #
     5  [ -f "$VIRTUAL_ENV/$VIRTUALENVWRAPPER_PROJECT_FILENAME"   -a "$VIRTUALENVWRAPPER_PROJECT_CD" = 1 ] &&     virtualenvwrapper_cd         "$(cat "$VIRTUAL_ENV/$VIRTUALENVWRAPPER_PROJECT_FILENAME")"
     6  # user_scripts
     7  #
     8  # Run user-provided scripts
     9  #
    10  [ -f "$VIRTUALENVWRAPPER_HOOK_DIR/postactivate" ] &&     source "$VIRTUALENVWRAPPER_HOOK_DIR/postactivate"
    11  [ -f "$VIRTUAL_ENV/$VIRTUALENVWRAPPER_ENV_BIN_DIR/postactivate" ] &&     source "$VIRTUAL_ENV/$VIRTUALENVWRAPPER_ENV_BIN_DIR/postactivate"
```

The installed virtualenvwrapper version:
```
$VIRTUALENVWRAPPER_PYTHON -m pip show virtualenvwrapper | grep -i "^Version"
Version: 4.7.1
```

It is related to issue #36.

**Comment by jorgenschaefer** [comment]
Heh. Thanks for the excellent bug report!

And meh! I knew that bug fix wouldn't work as expected. :-( Ok, back to the drawing board.

**Comment by pooyahub** [comment]
I still get the same error when I want to activate virtualenv in elpy config. Any help will be appreciated.

/bin/sh: 6: /tmp/pyvenv-virtualenvwrapper-*: source: not found
