### ISSUE TITLE
pyvenv-workon not working

### ISSUE THREAD

**Issue by 3noch** [jorgenschaefer/pyvenv#41]
I'm using Spacemacs and I run `M-x pyvenv-workon`, then select my virtual environment. But when I run any tests from within the project, they cannot find my modules.

**Comment by jorgenschaefer** [comment]
Hello and thanks for the report!
After `pyvenv-workon`, does `M-: (executable-find "python")` show the full path to the Python interpreter in your virtualenv?
How are you running your tests?

**Comment by 3noch** [comment]
Aha! That worked! It must be my testing setup then. I'm using [pytest](https://github.com/ionrock/pytest-el)

**Comment by jorgenschaefer** [comment]
I do not know `pytest-el` – make sure that whatever program it uses to run the tests uses the `python` interpreter in the current `PATH`, and not a hardcoded one.

**Comment by 3noch** [comment]
Thank you.
