### ISSUE TITLE
Tracking-mode: poor performance when no trailing slash in `pyvenv-activate`

### ISSUE THREAD

**Issue by bdarnell** [jorgenschaefer/pyvenv#42]
I discovered the hard way that `pyvenv-tracking-mode` performs very poorly when the `pyvenv-activate` variable is set to a value without a trailing slash. `pyvenv-track-virtualenv` will try to activate the virtualenv whenever `(not (equal pyvenv-workon pyvenv-virtual-env-name))`, but `pyvenv-virtual-env-name` is set to `(file-name-as-directory pyvenv-activate)`. If `file-name-as-directory` doesn't return `pyvenv-activate` unchanged (i.e. if there is no trailing slash), the tracking hook will reactivate the virtualenv on every keystroke.

I think `file-name-as-directory` should be used in the `pyvenv-track-virtualenv` comparison as well as where the variable is set.

**Comment by jorgenschaefer** [comment]
Thank you for the report! You are indeed correct.
