### ISSUE TITLE
Broken exec-path on Windows?

### ISSUE THREAD

**Issue by aagaard** [jorgenschaefer/pyvenv#43]
For me it seems that the pyvenv package is breaking my exec-path, when I activate the virtual environment. The exec-path looks like this originally:
`("c:/Users/sam/Envs/test/Scripts" "c:/ProgramData/Oracle/Java/javapath"` ...)

After I have activated the virtual environment my exec-path looks like this:
`("c" "\\Users\\sam\\Envs\\test\\Scripts;c" "\\ProgramData\\Oracle\\Java\\javapath;c" ...)`
Making it unable to find my bash, git, etc.

Do I miss something or is this a bug?

**Comment by jorgenschaefer** [comment]
This is indeed a bug (related to Windows). I suspect the above change does not actually fix it, though. Could you try and see if it does?

**Comment by aagaard** [comment]
The patch works! Thank you :+1:

**Comment by jorgenschaefer** [comment]
Oh, great – I was worried the backslashes would break things on Windows. Thank you for the report and the testing!
