### ISSUE TITLE
Access global binaries

### ISSUE THREAD

**Issue by Immortalin** [jorgenschaefer/pyvenv#45]
An option should be added to allow access to global binaries e.g. those install in `.local/bin` by pip since it doesn't always make sense to install tools such as yapf multiple times.

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the suggestion. I'm a bit confused what you are suggesting, though – just add `$HOME/.local/bin` to your `PATH` if you want to access programs there?

**Comment by Immortalin** [comment]
Virtualenv overrides this to prevent dependencies issues, however, a lot of emacs plugins requires external Python tools e.g. Jedi, yapf etc. hence it doesn't make sense to put them in `requirements.txt` as they are editor specific. A solution to this is to have some sort of hook to allow one to whitelist these specific binaries and to give a warning in the event of actual conflict with those in the venv(very rare as most of these tools are for code refactoring/completion purposes and rarely do they interfere with other libraries)

**Comment by jorgenschaefer** [comment]
> Virtualenv overrides this to prevent dependencies issues

Virtualenv activation does not remove anything from `PATH`. Are you thinking of the Python path? That's unrelated to binaries that can be found in `~/.local/bin`.

If you want to be able to access global Python libraries from your virtualenv, you can use `togleglobalsitepackages` from virtualenvwrapper.

**Comment by Immortalin** [comment]
@jorgenschaefer do you think an emacs based solution is possible? Using virtualenvwrapper means installing additional dependencies not to mention that this is an editor-specific problem i.e. the binaries that need to be accessed are for editor purposes

**Comment by jorgenschaefer** [comment]
> do you think an emacs based solution is possible?

That greatly depends on the problem. You seem to conflate the shell `PATH` with the Python path (I explained the difference above). Which one do you mean? :-)

**Comment by Immortalin** [comment]
Clarification: I mean python path. Right now to give venv access to global site packages means allowing it to have access to all global packages when you only need to allow the _editor_ to access a few specific ones e.g. `anaconda mode` dependencies.

**Comment by jorgenschaefer** [comment]
> I mean python path

`~/.local/bin` has nothing to do with `PYTHONPATH`. I remain confused?
