### ISSUE TITLE
Auto-generated scripts in `bin/` contain quotes around hashbang

### ISSUE THREAD

**Issue by alexreg** [jorgenschaefer/pyvenv#50]
Quotes around hashbangs are not recognised and are considered invalid syntax, at least on Bash on OS X 10.12. There's really no workaround to paths containing spaces, except maybe symlinking the directory in the path the contains the space. Maybe a warning message about this would be best.

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report. What auto-generated scripts are you talking about, and what did you do to generate them?

**Comment by alexreg** [comment]
The ones in the `bin/` folder. They’re generated automatically by pyvenv.

**Comment by jorgenschaefer** [comment]
> The ones in the `bin/` folder. They’re generated automatically by pyvenv.

pyvenv.el does not include any auto-generated scripts to my knowledge. Could you tell me _exactly_ what you are doing, _exactly_ what is happening, and _exactly_ what you did expect to happen? Thank you.

**Comment by alexreg** [comment]
From an empty directory with a space in its path:

```
pyenv venv/
source ./venv/bin/activate
pip
```

The result is:
```
-bash: /Users/me/Google Drive/foo/venv/bin/pip: "/Users/me/Google: bad interpreter: No such file or directory
```

And of course, I expect `pip` to run fine.

**Comment by jorgenschaefer** [comment]
I assume you mean `pyvenv`, not `pyenv`, there. `pyvenv` is part of Python. You are posting in the repository of `pyvenv.el`, a wrapper for `pyvenv` for the editor Emacs. I'm afraid I can not help you here. :-)

**Comment by alexreg** [comment]
Ah, rubbish… thanks.

**Comment by jorgenschaefer** [comment]
You're welcome. Good luck with the bug report!
