### ISSUE TITLE
set default venv directory

### ISSUE THREAD

**Issue by benswift** [jorgenschaefer/pyvenv#54]
I'm using [pyenv virtualenv](https://github.com/yyuu/pyenv-virtualenv) to create/manage virtualenvs, which means that they all get created in the same place (I'm using the suggested `/usr/local/var/pyenv/versions/`).

Is there a way to set a default directory for `pyenv-activate` to look in? It'd be nice if I didn't always have to navigate to `/usr/local/var/pyenv/versions/` to tell pyenv which virtualenv to activate.

Or am I doing it wrong?

**Comment by rgrinberg** [comment]
Can't you just set `WORKON_HOME=/usr/local/var/pyenv/versions` inside (using setenv) or outside of emacs?

**Comment by benswift** [comment]
Ok, cool. I'll just do that for now.
