### ISSUE TITLE
pyvenv-activate throws error about missing virtualenvwrapper module

### ISSUE THREAD

**Issue by lgp171188** [jorgenschaefer/pyvenv#55]
When I try to activate a virtualenv environment by running `M-x pyvenv-activate /path/to/venv RET` pyvenv prints an error from `pre_activate` and `post_activate` hooks with the an error looking like

    Output from the virtualenvwrapper hook pre_activate:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'virtualenvwrapper'
 
Does `pyvenv-activate` require `virtualenvwrapper`? I had a quick look at the `pyvenv.el` source and it looks to be the case. But I am raising this issue because I remember using `pyvenv-activate` without having `virtualenvwrapper` installed and it worked fine.

Feel free to change this issue into a question, if appropriate. Thanks!

**Comment by jorgenschaefer** [comment]
pyvenv _ought_ to work without virtualenvwrapper, but looking at the code, some recent unrelated changes broke the check whether virtualenvwrapper is installed at all …

Does `M-: (getenv "WORKON_HOME")` return `nil` for you?

**Comment by lgp171188** [comment]
Yes, it returns `nil` on my Arch Linux desktop where I have been getting this error. I also checked the same on my Macbook running the latest Emacs where I do not see this error and it returns `nil` even there.

Arch Linux uses the python3 interpreter as the default python interpreter and I am using the built-in `venv` module to create the virtualenv environment. I had installed `virtualenvwrapper` on this computer some time back, but I have completely removed it. I also checked all my configuration files in my home directory and `/etc` and couldn't find any traces of `virtualenvwrapper`.

This line https://github.com/jorgenschaefer/pyvenv/blob/master/pyvenv.el#L160 prints the same error for `pre_activate` hook but works fine on the other computer where I do not see this error. While this might indicate some problem with one of the computers, I am not sure what else I can check.

**Comment by lgp171188** [comment]
The `pyvenv-pre-activate-hooks` is `nil` but still `(run-hooks 'pyvenv-pre-activate-hooks)` prints this error

**Comment by jorgenschaefer** [comment]
Yeah. https://github.com/jorgenschaefer/pyvenv/blob/master/pyvenv.el#L359 should probabbly be expanded to check for virtualenvwrapper – basically, replace that call to `pyvenv-hook-dir` with `pyvenv-virtualenvwrapper-supported` or something. That function then should just check for `(getenv "WORKON_HOME")`.

**Comment by jorgenschaefer** [comment]
Actually. L380 should be updated to also check for ModuleNotFoundError I guess.

**Comment by jorgenschaefer** [comment]
Could you see if that commit fixes things for you?

**Comment by lgp171188** [comment]
I tried the changes in that commit and I now get

    Output from the virtualenvwrapper hook post_activate:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'virtualenvwrapper'

Note that this is now an error for the `post_activate` hook and not the `pre_activate` hook as reported originally.

**Comment by jorgenschaefer** [comment]
Hm. The two hooks use the same function to run this code. First, it should not run at all because `WORKON_HOME` is not set. And second, it should ignore that error. Sorry, but are you sure you reloaded the file? :-)

**Comment by lgp171188** [comment]
I am not sure if I did it right the previous time, so I did the following things.

I renamed the `pyvenv.el` in `~/.emacs.d/elpa/pyvenv-1.9` directory to `pyvenv` and replaced it with the file from the commit. Then I also deleted all the `.elc` files from my `~/.emacs.d/` folder and restarted emacs. Now `pyvenv-activate RET /path/to/venv RET` doesn't throw this error and I see `[venv]` in the modeline.

When I opened the shell (`M-x shell`) and tried running `which python` it was pointing to the sytem python `/usr/bin/python` and it could not find `pip`.

**Comment by jorgenschaefer** [comment]
You can just `M-x load-file RET downloadedpyvenv.el RET` … Please use `M-: (executable-find "python")` to check if the virtualenv is active. If the shell for `M-x shell` was running before, it won't change the environment for it.

**Comment by lgp171188** [comment]
On a newly opened emacs, I used the `load-file` function to load the downloaded file. The `executable-find` function is able to find the `python` and `pip` binaries present in my virtualenv environment after activating it with `M-x pyvenv-activate`.

After that, I opened the shell by running `M-x shell` and it cannot find the binaries inside my virtualenv.

**Comment by jorgenschaefer** [comment]
Hm. Does `(getenv "PATH")` include the virtualenv?

**Comment by lgp171188** [comment]
Yes it does. I can see that the virtualenv directory is the first directory.

But in the shell loaded by `M-x shell` after activating the virtualenv using `pyvenv-activate`, I see that the `VIRTUAL_ENV` environment variable has been set and is pointing correctly to my virtualenv but the `PATH` is not modified to include the virtualenv bin directory. I am using zsh as my shell. The contents of `PATH` are exactly the same as customized in `~/.zshrc` where I have added some additional directories to `PATH`.

Since this issue with the shell is not related directly to this issue, I can create a new issue if you think this is not expected behaviour.

**Comment by jorgenschaefer** [comment]
I am afraid this is an issue with your shell, not with pyvenv. If you configure your shell to override `PATH`, there is preciously little pyvenv can do about it. Do not override `PATH` in your shell configuration.

**Comment by lgp171188** [comment]
I am only adding directories to `PATH` and not overriding it, using something like `export PATH=$PATH:~/opt/bin`. Just to check if that was causing the issue, I commented it out and opened a new shell to confirm that the `PATH` is not modified. Then I opened emacs, activated the virtualenv and then opened the shell by running `M-x shell`.

I echoed `$PATH` and I do not see the virtualenv directories in it even now.

**Comment by jorgenschaefer** [comment]
When `PATH` is set correctly in `process-environment`, Emacs will set it for subprocesses. If they do not see it correctly, I do not know what else I could do about it.

**Comment by lgp171188** [comment]
This appears to be specific to zsh and when I tested on a different user account using bash, it works properly. Closing this issue as it has been resolved. Thanks!

**Comment by jorgenschaefer** [comment]
You are welcome, and glad this could be resolved! Good luck finding the problem in zsh :-)

**Comment by bersace** [comment]
@lgp171188 you should set `WORKON_HOME` in your `.profile`, not `.zshrc` unless you run emacs from your zsh. Isn't it ?

**Comment by bersace** [comment]
The same for `VIRTUALENVWRAPPER_PYTHON`.
