### ISSUE TITLE
Allow use of new python3+ venv module

### ISSUE THREAD

**Issue by saltycraig** [jorgenschaefer/pyvenv#58]
I use this plugin with elpy, but I only use python3.4+. The 'pyvenv' script that was introduced in around 3.0 has been deprecated as of 3.6+ (https://docs.python.org/3/library/venv.html#module-venv) and it is now recommended to use ```python3 -m venv <myenv>``` for all new python3.3+ projects, as 'venv' was added to the standard library.

My request is that pyvenv is able to make use of the new stdlib module if python3.3+ is detected.

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report. pyvenv does not use the virtualenv or pyvenv scripts at all, as it is not meant to create new virtualenvs, just to use existing ones. What support are you looking for?

**Comment by saltycraig** [comment]
Sorry, I did not notice that, I'm still learning elisp! Thanks for the reply.
