### ISSUE TITLE
pyvenv-workon doesn't set proper default-directory before calling virtualenvwrapper.hook_loader, which can result in conflicts

### ISSUE THREAD

**Issue by posita** [jorgenschaefer/pyvenv#59]
I'm not entirely sure this is a bug, but it's unexpected behavior ~that seems to suggest that `pyvenv-workon` is incompatible with `.dir-locals.el`~.

_**UPDATE**: See [this comment](#issuecomment-322349301) below._

Here's how to reproduce:

```sh
$ mkdir …/test-pyvenv-dir-locals
$ mkvirtualenv -a …/test-pyvenv-dir-locals --python=python3 test-pyvenv-dir-locals
# …
$ pwd
…/test-pyvenv-dir-locals
$ cat >.dir-locals.el <<EOF
heredoc> ((python-mode . ((eval . (pyvenv-workon "test-pyvenv-dir-locals")))))
heredoc> EOF
$ mkdir -p spamhameggs/email
$ touch spamhameggs/__init__.py spamhameggs/foobarbaz.py spamhameggs/email/__init__.py
$ cat >spamhameggs/email/__init__.py <<EOF
heredoc> This is not syntactically valid!!!
heredoc> EOF
$ ls -Ra .
.               ..              .dir-locals.el  spamhameggs

./spamhameggs:
.               ..              __init__.py     email           foobarbaz.py

./spamhameggs/email:
.               ..              __init__.py
```

From within Emacs, do `C-f` `…/test-pyvenv-dir-locals/spamhameggs/foobarbaz.py`. You'll get a local variable warning from the `/.dir-locals.el` file. Type `y`. You will get the following error:

```py
Output from the virtualenvwrapper hook post_activate:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/…/.virtualenvwrapper-bootstrap/lib/python3.6/site-packages/virtualenvwrapper/hook_loader.py", line 16, in <module>
    from stevedore import ExtensionManager
  File "/…/.virtualenvwrapper-bootstrap/lib/python3.6/site-packages/stevedore/__init__.py", line 11, in <module>
    from .extension import ExtensionManager
  File "/…/.virtualenvwrapper-bootstrap/lib/python3.6/site-packages/stevedore/extension.py", line 17, in <module>
    import pkg_resources
  File "/…/.virtualenvwrapper-bootstrap/lib/python3.6/site-packages/pkg_resources/__init__.py", line 36, in <module>
    import email.parser
  File "/…/test-pyvenv-dir-locals/spamhameggs/email/__init__.py", line 1
    This is not syntactically valid!!!
                                  ^
SyntaxError: invalid syntax
```

It appears that ~the parent directory of the file being edited~ _`default-directory`_ is being added at the head of `sys.path` before evaluating `workon`, which can result in conflicts with installed packages (in this case `email` from the standard library).

**Comment by posita** [comment]
Actually, I don't think this has anything to do with `.dir-locals.el`. Here's a simpler way to reproduce:

1. Use the steps listed in the original post (feel free to skip the creation of `.dir-locals.el`).
1. In Emacs, do `M-x` `pyvenv-deactivate` to make sure no virtualenv is activated.
1. In Emacs, do `C-f` `…/test-pyvenv-dir-locals/spamhameggs/foobarbaz.py`.
1. With `…/foobarbaz.py` being the active buffer, do `M-x` `pyvenv-workon` `test-pyvenv-dir-locals`.

You'll get a similar error, strongly supporting the final observation above:

> It appears that the parent directory of the file being edited is being added at the head of `sys.path`, which overrides common package names (in this case `email`).

This doesn't appear to have anything to do with `.dir-locals.el` though. It's just how I discovered the behavior.

**Comment by jorgenschaefer** [comment]
Nice catch. I guess this is related to from which directory the virtualenvwrapper scripts are invoked from. I suspect this is not a problem with using virtualenvwrapper's `workon` directly? I wonder what working directory that uses. Hm.

**Comment by posita** [comment]
From https://docs.python.org/3/library/sys.html#sys.path and https://docs.python.org/2/library/sys.html#sys.path (_emphasis_ in original):

> As initialized upon program startup, the first item of this list, `path[0]`, is the directory containing the script that was used to invoke the Python interpreter. If the script directory is not available (e.g. if the interpreter is invoked interactively or if the script is read from standard input), `path[0]` is the empty string, which directs Python to search modules in the current directory first. Notice that the script directory is inserted _before_ the entries inserted as a result of [`PYTHONPATH`](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONPATH).

While not documented clearly, the above _also_ applies to scripts invoked via `python -m …`. The shell version of `workon` calls `virtualenvwrapper_run_hook`, which eventually calls:

`… && "$VIRTUALENVWRAPPER_PYTHON" -m 'virtualenvwrapper.hook_loader' …`

This sets the first element of `sys.path` to the parent directory of the `virtualenvwrapper.hook_loader` module. This means that `workon` should be callable from anywhere, which is consistent with my observation.

For _some_ reason that is not (yet) clear to me, when `pyvenv-workon` is called `sys.path` appears to end up having the parent directory of the file in the active buffer as its first element, which is why the conflicts happen.

**Comment by posita** [comment]
I _think_ I see the issue. From [`pyvenv.el`#L366-L375](/pyvenv/blob/91c47b8d2608ccbcac2eba91f0e36b422101ce55/pyvenv.el#L366-L375):

```lisp
…
              (apply #'call-process
                     pyvenv-virtualenvwrapper-python
                     nil t nil
                     "-c"
                     "from virtualenvwrapper.hook_loader import main; main()"
                     "--script" tmpfile
                     (if (getenv "HOOK_VERBOSE_OPTION")
                         (cons (getenv "HOOK_VERBOSE_OPTION")
                               (cons hook args))
                       (cons hook args)))
…
```

`python -c …` will always insert `''` into the head of `sys.path`:

```
$ python -c 'import sys ; print(sys.path)' --script spam.py ham eggs.py
['', …]
```

I haven't tested this, but one solution _might_ be to something like this instead (which more closely mirrors the shell version):

```lisp
…
              (apply #'call-process
                     pyvenv-virtualenvwrapper-python
                     nil t nil
                     ;; call the hook loader as a module to make sure sys.path
                     ;; is set up correctly
                     "-m" "virtualenvwrapper.hook_loader"
                     "--script" tmpfile
                     (if (getenv "HOOK_VERBOSE_OPTION")
                         (cons (getenv "HOOK_VERBOSE_OPTION")
                               (cons hook args))
                       (cons hook args)))
…
```

**Comment by posita** [comment]
Hmmm…I tried my change from https://github.com/jorgenschaefer/pyvenv/issues/59#issuecomment-323545834, but it apparently had no effect. (I still got the same error.)

As an aside, I think `"-m" "virtualenvwrapper.hook_loader"` is more idiomatic than `"-c" "…"`. It just doesn't seem to fix this issue.

**Comment by posita** [comment]
More tinkering has led to another clue. I can _only_ reproduce this when `VIRTUALENVWRAPPER_PYTHON` is set. This is mirrored in the shell behavior (sort of):

```
$ cd /…/test-pyvenv-dir-locals/spamhameggs
$ echo "${VIRTUALENVWRAPPER_PYTHON}"
/…/.virtualenvwrapper-bootstrap/bin/python
$ "${VIRTUALENVWRAPPER_PYTHON}" -m virtualenvwrapper.hook_loader
Traceback (most recent call last):
  File "/…/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/…/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/…/.virtualenvwrapper-bootstrap/lib/python3.6/site-packages/virtualenvwrapper/hook_loader.py", line 16, in <module>
    from stevedore import ExtensionManager
  File "/…/.virtualenvwrapper-bootstrap/lib/python3.6/site-packages/stevedore/__init__.py", line 11, in <module>
    from .extension import ExtensionManager
  File "/…/.virtualenvwrapper-bootstrap/lib/python3.6/site-packages/stevedore/extension.py", line 17, in <module>
    import pkg_resources
  File "/…/.virtualenvwrapper-bootstrap/lib/python3.6/site-packages/pkg_resources/__init__.py", line 36, in <module>
    import email.parser
  File "/…/test-pyvenv-dir-locals/spamhameggs/email/__init__.py", line 1
    This is not syntactically valid!
                                  ^
SyntaxError: invalid syntax
```

Note that in the shell implementation, `virtualenvwrapper_run_hook` _explicitly_ changes the working directory to `WORKON_HOME` before invoking `hook_loader`:

`virtualenvwrapper_cd "$WORKON_HOME" && "$VIRTUALENVWRAPPER_PYTHON" -m 'virtualenvwrapper.hook_loader' $HOOK_VERBOSE_OPTION --script "$hook_script" "$@"`

**Comment by posita** [comment]
From https://www.gnu.org/software/emacs/manual/html_node/elisp/Synchronous-Processes.html:

> The current working directory of the subprocess is set to the current buffer's value of `default-directory` if that is local (as determined by `unhandled-file-name-directory`), or `"~"` otherwise. If you want to run a process in a remote directory use `process-file`.

**Comment by jorgenschaefer** [comment]
This is some absolutely awesome debugging work – thank you :-)
