### ISSUE TITLE
Support workon in Windows via virtualenvwrapper-win

### ISSUE THREAD

**Issue by gilch** [jorgenschaefer/pyvenv#61]
[virtualenvwrapper has a Windows port](https://github.com/davidmarble/virtualenvwrapper-win/)

`pyvenv-activate` is working on Windows now. But `pyvenv-workon` "Can't find a workon home directory, set $WORKON_HOME". Setting `WORKON_HOME` (or `$WORKON_HOME`) doesn't work.

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report. I guess on Windows, that would be `%WORKON_HOME%`, i.e. the environment variable, so that `(getenv "WORKON_HOME")` returns the correct directory. How did you set `WORKON_HOME`?

**Comment by gilch** [comment]
I've updated via MELPA, and can no longer reproduce this issue. It seems to find the virtual environments, but I get a different error now.
```
apply: Searching for program: No such file or directory, python
```
The `python` command is available in an active virtualenv, but not from Windows cmd normally, which uses the `py` launcher instead.

Is pyvenv supposed to be using the `python` from the virtualenv here?

**Comment by gilch** [comment]
It looks like `pyvenv-activate` is also broken now. When `WORKON_HOME` is set, I get the same error about `python` not existing. But if I delete the environment variable, then I can use `pyvenv-activate`, but I have to find the Envs folder manually.

**Comment by jorgenschaefer** [comment]
That sounds extremely weird. I'm afraid I do not have access to a Windows system, so if you can find out what's going on there, that'd be great …

**Comment by gilch** [comment]
Manually setting `VIRTUALENVWRAPPER_PYTHON` to `py` makes it work. 

That makes me think that changing
```elisp
(defcustom pyvenv-virtualenvwrapper-python
  (or (getenv "VIRTUALENVWRAPPER_PYTHON")
      (executable-find "python")
      "python")
```
to
```
(defcustom pyvenv-virtualenvwrapper-python
  (or (getenv "VIRTUALENVWRAPPER_PYTHON")
      (executable-find "python")
      (executable-find "py")
      "python")
```
would make it work on Windows.

**Comment by jorgenschaefer** [comment]
Why is it called `py` on Windows? That's not how it worked when I used Windows last …

**Comment by gilch** [comment]
See [PEP 397](https://www.python.org/dev/peps/pep-0397/).

**Comment by jorgenschaefer** [comment]
Ye gods. Why. :-( Thank you.
