### ISSUE TITLE
pyvenv-activate doesn't pick packages installed from virtualenv

### ISSUE THREAD

**Issue by canicola** [jorgenschaefer/pyvenv#62]
I have the following question regarding pyvenv-activate. 
I point via pyvenv-activate to the correct bin/ folder of my virtualenv of my python project.
When I select a line in my xyz.py file and hit `C-Enter` a new window pops up running a Python Interpreter. However, it seems this python interpreter is not linked to the virtualenv as I thought it would be. Importing a module which is only installed within the virtualenv is not found and throws an error.

On the other hand running a term mode in emacs and activating the virtualenv via `source /virtualenv/bin/activate` and running a python interpreter from the term emulator is correctly linked to the virtualenv packages, i.e. it finds the asked module. Do I wrongly use the pyvenv-activate or is this a bug?

**Comment by jorgenschaefer** [comment]
> I point via pyvenv-activate to the correct bin/ folder of my virtualenv of my python project.

You should point pyvenv-activate to the directory of your virtualenv, which should be distinct from your project directory. In your case, `/virtualenv`. Does that fix the problem?

**Comment by canicola** [comment]
Hi Jörgen
Yes it does! Many thanks for the fast respond.
