### ISSUE TITLE
conda: buffer containing "No module named virtualenvwrapper" is shown

### ISSUE THREAD

**Issue by immerrr** [jorgenschaefer/pyvenv#63]
Hi,

and thank you for such a great package. After updating pyvenv recently I started seeing a buffer telling me
```
Output from the virtualenvwrapper hook pre_deactivate:

/usr/bin/python: No module named virtualenvwrapper
```

I've checked the sources, and there are clear efforts for that not to happen, but probably the regexp that checks for `ImportError|ModuleNotFoundError` is too strict, since my "no module named" message doesn't refer to the error class. FTR, the OS is Ubuntu 16.04 with /usr/bin/python being 
```
$ /usr/bin/python --version
Python 2.7.12
```

**Comment by jorgenschaefer** [comment]
Thank you for the report! Could you check if this fix solves your problem? :-)

**Comment by immerrr** [comment]
Looks like it should work, I'll try it out as soon as it gets to melpa. Thank you!

**Comment by jorgenschaefer** [comment]
Please re-open this if it still breaks! :-)
