### ISSUE TITLE
Throw wrong type argument stringp nil error when workon conda virtual environment on Windows

### ISSUE THREAD

**Issue by maobaoqi** [jorgenschaefer/pyvenv#70]
Hi,
I meet an error when run pyvenv-workon. I use conda on Windows.
There is debug information. 

![snipaste_20180411_101939](https://user-images.githubusercontent.com/3353791/38593058-0afb27ac-3d72-11e8-952f-a1123499dcf3.png)

**Comment by jorgenschaefer** [comment]
Hello and thanks for the report! What's the value of `shell-file-name`? (`C-h v shell-file-name`)

**Comment by maobaoqi** [comment]
@jorgenschaefer Thanks for your reply!
I check the shell-file-name value and there is the result :
![snipaste_20180414_103410](https://user-images.githubusercontent.com/3353791/38763494-b167c852-3fcf-11e8-97f1-463d4e88ba99.png)

**Comment by jorgenschaefer** [comment]
Ah … I think I found the problem. Windows does  not have a sh or bash. Could you try if this fix solves your problem?
