### ISSUE TITLE
pyvenv-exec-shell: source: not found

### ISSUE THREAD

**Issue by hitswint** [jorgenschaefer/pyvenv#71]
When I'm trying to activate pyvenv, i get the following errors:
Output from the virtualenvwrapper hook post_activate:/bin/sh: 11: /tmp/pyvenv-virtualenvwrapper-20063bCc: source: not found.
The value of pyvenv-exec-shell is "/bin/sh", everything turns out to be fine if i changed that to "/bin/bash". It seems like "source" command is not available for /bin/sh.

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the report! Apparently Debian's `ash` does not support this, so pyvenv now prefers bash over sh. I hope this fixes the problem for you in the default config, too :-)
