### ISSUE TITLE
Is there a function that returns value indicating whether virtualenvironment is active/inactive?

### ISSUE THREAD

**Issue by avocadoras** [jorgenschaefer/pyvenv#88]
I would like to know if there is a function that would tell me whether there is a current active virtual environment in my root (git) project. I would use this information to build a `pyvenv-dwim` function that would activate or deactivate the virtual environment, if it is active or vice-versa.

**Comment by winpat** [comment]
There is a variable called `pyvenv-virtual-env` which stores the path to the currently active virtualenv. If no virtualenv is active, the variable is set to `nil`.

**Comment by avocadoras** [comment]
Is there a way to interactively call `(pyvenv-activate)` inside an interactive function? Right now I get 
```
if: Wrong number of arguments: (1 . 1), 0
``` 

error with 
```elisp
(defun pyvenv-activate-dwim ()
  (interactive)
  (if pyvenv-virtual-env
      (pyvenv-deactivate)
    (pyvenv-activate)))

(add-hook 'elpy-mode-hook (lambda () (define-key elpy-mode-map (kbd "C-c v") 'pyvenv-activate-dwim)))
```

and this variation seems to do nothing
```elisp 
(defun pyvenv-activate-dwim ()
  (interactive)
  (if pyvenv-virtual-env
      (pyvenv-deactivate)
    (lambda () (pyvenv-activate))))
```

**Comment by winpat** [comment]
@avocadoras I think what you are looking for is `(call-interactively 'pyvenv-activate)`.

**Comment by avocadoras** [comment]
@winpat yes, that was it. Thanks!
