### ISSUE TITLE
Automatically restart lsp-mode after activating pyvenv?

### ISSUE THREAD

**Issue by ianpan870102** [jorgenschaefer/pyvenv#95]
So my workflow is always as such:

1. Go to a python buffer (which subsequently starts the lsp server)
2. Interactively activate the virtual environment with pyvenv-activate.
3. Restart the lsp server, since I need lsp to pick up the venv change.

I wonder if I can combine step 2 and step 3 together -- when I call the pyvenv-activate function, it subsequently restarts the lsp-workspace for me.

I've tried something like
```emacs-lisp
(defun my-pyvenv-activate ()
  (interactive)
  (pyvenv-activate)
  (lsp-workspace-restart))
```
But it says `wrong number of arguments: (1 . 1), 0`

**Comment by jorgenschaefer** [comment]
You have to call `pyvenv-activate` with an argument. To make it ask for the environment, use `(call-interactively 'pyvenv-activate)`.

A better way might be to use `(add-hook 'pyvenv-post-activate-hooks 'lsp-workspace-restart)` - that way, you can just use `pyvenv-activate` and lsp will restart automatically.

**Comment by ianpan870102** [comment]
@jorgenschaefer  Thanks so much for the advice! A quick modification got your snippet working. Since `lsp-workspace-restart` also takes an argument, I've changed the `add-hook` to the following:
```emacs-lisp
(add-hook 'pyvenv-post-activate-hooks
          #'(lambda ()
              (call-interactively #'lsp-workspace-restart)))
```
