### ISSUE TITLE
Please, support python3 executable by default

### ISSUE THREAD

**Issue by dogsleg** [jorgenschaefer/pyvenv#99]
Currently pyvenv searches for python executable, but since the end of life cycle of Python2 and finishing migration to Python3 some distros (e. g., Debian) stop shipping python symlink to python3 executable, which makes pyvenv unhappy on such distros. Please, also support python3 executable by default.

For some more information, please, see [Debian bug report #975560](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=975560).

Thanks for your work on pyvenv!

**Comment by jorgenschaefer** [comment]
Thanks for the report! Could you check if the latest commit fixes this already?

**Comment by dogsleg** [comment]
Calling pyvenv-create produces the following for me:

```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  file-name-directory(nil)
  (read-file-name "Python interpreter to use: " (file-name-directory (executable-find "python")) nil nil "python")
  (list (read-from-minibuffer "Name of virtual environment: ") (read-file-name "Python interpreter to use: " (file-name-directory (executable-find "python")) nil nil "python"))
  #<subr call-interactively>(pyvenv-create record nil)
```

**Comment by dogsleg** [comment]
But pyvenv-activate does work.

**Comment by jorgenschaefer** [comment]
Missed the call in pyvenv-create. I rewrote the logic there to re-use the one used for pyvenv-activate. Does this work on your system now? :-)

**Comment by dogsleg** [comment]
Yes, now it works as expected. Thanks!
